In [1]:
!pip install tensorflow

In [2]:
!pip install textblob

In [3]:
!pip install fuzzywuzzy

In [4]:
!pip install nltk

In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
# import re

# Reading corpus the text file
with open("A-Pair-of-Schoolgirls.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()

In [3]:
mytext

'\ufeffThe Project Gutenberg eBook of A Pair of Schoolgirls: A Story of School Days\n    \nThis ebook is for the use of anyone anywhere in the United States and\nmost other parts of the world at no cost and with almost no restrictions\nwhatsoever. You may copy it, give it away or re-use it under the terms\nof the Project Gutenberg License included with this ebook or online\nat www.gutenberg.org. If you are not located in the United States,\nyou will have to check the laws of the country where you are located\nbefore using this eBook.\n\nTitle: A Pair of Schoolgirls: A Story of School Days\n\n\nAuthor: Angela Brazil\n\nIllustrator: John Campbell\n\nRelease date: August 9, 2010 [eBook #33389]\n\nLanguage: English\n\n\n\n*** START OF THE PROJECT GUTENBERG EBOOK A PAIR OF SCHOOLGIRLS: A STORY OF SCHOOL DAYS ***\n\n\n\nProduced by Suzanne Shell and the Online Distributed\nProofreading Team at http://www.pgdp.net\n\n\n\n\n\n\n\n\n\nA Pair of Schoolgirls\n\n\n\n\n    By ANGELA BRAZIL\n\n    "

In [7]:
# # strip multiple whitespaces
# mytext = ' '.join(mytext.split())

# # convert to lower case
# mytext = mytext.lower()

In [8]:
# """Removes punctuation and numbers from a given text.
#     ----------
#     text : str
#         The text to remove punctuation and numbers from.

#     Returns
#     -------
#     str
#         The text with punctuation and numbers removed.
#     """
# mytext = ''.join([char for char in mytext if char.isalpha() or char == ' '])

In [9]:
# emoji = re.compile("["
#                        u"\U0001F600-\U0001FFFF"  # emoticons
#                        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
#                        u"\U0001F680-\U0001F6FF"  # transport & map symbols
#                        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
#                        u"\U00002702-\U000027B0"
#                        u"\U000024C2-\U0001F251"
#                        "]+", flags=re.UNICODE)
# mytext = emoji.sub(r'', mytext)

In [10]:
# from textblob import TextBlob
# blob = TextBlob(mytext)
# corrected_text = blob.correct()
# mytext = corrected_text.string

In [11]:
# from fuzzywuzzy import process, fuzz
# from nltk.corpus import words

# corpus = words.words()

#     # Split the text into a list of words
# words = mytext.split()

#     # Correct each word in the text
# fuzzy_matched_words = []
# for word in words:
#     # Find the closest match to the word in the corpus
#     closest_match = process.extractOne(word, corpus, scorer=fuzz.ratio)
#     # If the closest match is a perfect match, use it
#     if closest_match[1] > 85:
#         fuzzy_matched_words.append(closest_match[0])

# # Join the corrected words into a string
# fuzzy_matched_text = " ".join(fuzzy_matched_words)

In [12]:
# import nltk  # natural language toolkit
# nltk.download()
# """Tokenizes a given text into a list of words.

#     Parameters
#     ----------
#     text : str
#         The text to tokenize. E.g. "This is a sentence"

#     Returns
#     -------
#     list
#         A list of words. E.g. ["This", "is", "a", "sentence"]
#     """

#     # split text into tokens (words) - also gets rid of multiple whitespaces
# tokens = nltk.word_tokenize(mytext)

In [4]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [5]:
mytokenizer.word_index

{'the': 1,
 'to': 2,
 'and': 3,
 'of': 4,
 'a': 5,
 'she': 6,
 'her': 7,
 'i': 8,
 'in': 9,
 'was': 10,
 'it': 11,
 'you': 12,
 'at': 13,
 'that': 14,
 'had': 15,
 'dorothy': 16,
 'for': 17,
 'with': 18,
 'be': 19,
 'not': 20,
 'on': 21,
 'as': 22,
 'so': 23,
 'but': 24,
 'have': 25,
 'were': 26,
 'miss': 27,
 'if': 28,
 'all': 29,
 'is': 30,
 'or': 31,
 'said': 32,
 'me': 33,
 'my': 34,
 'from': 35,
 'by': 36,
 'one': 37,
 'we': 38,
 'this': 39,
 'no': 40,
 "it's": 41,
 'up': 42,
 'been': 43,
 'there': 44,
 'who': 45,
 'an': 46,
 'do': 47,
 'they': 48,
 'out': 49,
 'alison': 50,
 'your': 51,
 'any': 52,
 'what': 53,
 'when': 54,
 "don't": 55,
 'could': 56,
 'would': 57,
 'school': 58,
 'are': 59,
 'them': 60,
 'girls': 61,
 'only': 62,
 'must': 63,
 "i'm": 64,
 'little': 65,
 'then': 66,
 'which': 67,
 'very': 68,
 'their': 69,
 'he': 70,
 'like': 71,
 'well': 72,
 'about': 73,
 'hope': 74,
 'into': 75,
 'will': 76,
 'can': 77,
 'time': 78,
 'over': 79,
 'see': 80,
 'go': 81,
 'hersel

In [6]:
my_input_sequences = []
for line in mytext.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [8]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [9]:
input_sequences[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0, 3360,   94,  206])

In [10]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [11]:
X[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0, 3360,   94])

In [12]:
y

array([  94,  206,  536, ...,   73,  182, 1032])

In [13]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [14]:
y[1]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [15]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 17, 100)           666900    
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 6669)              1007019   
                                                                 
Total params: 1824519 (6.96 MB)
Trainable params: 1824519 (6.96 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [16]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=1)


Epoch 1/100


1645/1645 [==============================] - 75s 44ms/step - loss: 6.6881 - accuracy: 0.0630
Epoch 2/100
1645/1645 [==============================] - 73s 44ms/step - loss: 6.0409 - accuracy: 0.0973
Epoch 3/100
1645/1645 [==============================] - 71s 43ms/step - loss: 5.6111 - accuracy: 0.1256
Epoch 4/100
1645/1645 [==============================] - 72s 44ms/step - loss: 5.2555 - accuracy: 0.1454
Epoch 5/100
1645/1645 [==============================] - 72s 44ms/step - loss: 4.9114 - accuracy: 0.1628
Epoch 6/100
1645/1645 [==============================] - 64s 39ms/step - loss: 4.5799 - accuracy: 0.1801
Epoch 7/100
1645/1645 [==============================] - 55s 33ms/step - loss: 4.2586 - accuracy: 0.2037
Epoch 8/100
1645/1645 [==============================] - 54s 33ms/step - loss: 3.9482 - accuracy: 0.2352
Epoch 9/100
1645/1645 [==============================] - 44s 27ms/step - loss: 3.6533 - accuracy: 0.2717
Epoch 10/100
1645/1645 [============================

In [17]:
input_text = "game"
predict_next_words= 10

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[3037]
1/1 [==============================] - 1s 859ms/step
[3037, 3]
1/1 [==============================] - 0s 46ms/step
[3037, 3, 1909]
1/1 [==============================] - 0s 42ms/step
[3037, 3, 1909, 3]
1/1 [==============================] - 0s 42ms/step
[3037, 3, 1909, 3, 1]
1/1 [==============================] - 0s 46ms/step
[3037, 3, 1909, 3, 1, 3224]
1/1 [==============================] - 0s 41ms/step
[3037, 3, 1909, 3, 1, 3224, 204]
1/1 [==============================] - 0s 45ms/step
[3037, 3, 1909, 3, 1, 3224, 204, 1]
1/1 [==============================] - 0s 53ms/step
[3037, 3, 1909, 3, 1, 3224, 204, 1, 238]
1/1 [==============================] - 0s 42ms/step
[3037, 3, 1909, 3, 1, 3224, 204, 1, 238, 161]
1/1 [==============================] - 0s 39ms/step
game and false and the medical left the next train together


In [23]:
input_text = "dress"
predict_next_words= 20

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[291]
1/1 [==============================] - 0s 38ms/step
[291, 1]
1/1 [==============================] - 0s 53ms/step
[291, 1, 2193]
1/1 [==============================] - 0s 53ms/step
[291, 1, 2193, 1562]
1/1 [==============================] - 0s 62ms/step
[291, 1, 2193, 1562, 75]
1/1 [==============================] - 0s 92ms/step
[291, 1, 2193, 1562, 75, 5]
1/1 [==============================] - 0s 61ms/step
[291, 1, 2193, 1562, 75, 5, 1360]
1/1 [==============================] - 0s 50ms/step
[291, 1, 2193, 1562, 75, 5, 1360, 4]
1/1 [==============================] - 0s 93ms/step
[291, 1, 2193, 1562, 75, 5, 1360, 4, 6452]
1/1 [==============================] - 0s 57ms/step
[291, 1, 2193, 1562, 75, 5, 1360, 4, 6452, 16]
1/1 [==============================] - 0s 55ms/step
[291, 1, 2193, 1562, 75, 5, 1360, 4, 6452, 16, 15]
1/1 [==============================] - 0s 58ms/step
[291, 1, 2193, 1562, 75, 5, 1360, 4, 6452, 16, 15, 490]
1/1 [==============================] - 0s 56ms/step
[291

In [24]:
import pickle
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
pickle.dump(model,open("next-word.pkl","wb"))
model.save("next-word.h5")


In [25]:
import pickle
from tensorflow.keras.preprocessing.text import Tokenizer

# Assuming you have already loaded and preprocessed your text into 'mytext'
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])

# Save the tokenizer to a file
with open("tokenizer.pkl", 'wb') as file:
    pickle.dump(mytokenizer, file)